const jokes = [
  "Adopt an ant farm",
  "Get really into lock-picking",
  "Download TikTok",
  "Adopt a pet raccoon",
  "do something involving a lizard",
  "Get really into day trading ",
  "Get a planet fitness membership",
  "Buy kettlebells",
  "Become a barista at a cute coffee shop and quit two-weeks later",
  "Start a SoundCloud and learn to rap",
  "Become an e-girl",
  "Start making kombucha",
  "Create a quarter-life crisis hotline instead of actually getting a job",
  "Start an alt-twitter",
  "Move to Ohio",
  "Move to New York",
  "Move to Colorado",
  "Move to California",
  "Get a nose piercing",
  "Get a tattoo",
  "Dye your hair",
  "Start listening to way too much Hozier",
  "Buy a tiny a house",
  "Buy a 3D printer",
  "Start making memes for Instagram",
  "Start a creator house",
  "Get married too soon",
  "Start a podcast about dating",
  "Start a podcast about crypto",
  "Get really into doge coin",
  "Rob a bank",
  "Start going to therapy",
  "Become low-key alcoholic",
  "Become high-key alcoholic",
  "Quit your salaried job to become a bartender",
  "Start brewing IPAs in your kitchen",
  "Get really into 3D printing ",
  "Start knitting scarves",
  "Take a trip to Miami",
  "Start an agency",
  "Tell all your friends you’re going to become a pilot",
  "Tye-dye EVERYTHING in your closet",
  "Start a depop even though you own no clothes",
  "Start a podcast",
  "Start doing pottery",
  "Start a band",
  "Start a skater girl gang",
  "Binge watch all the documentaries",
];

module.exports = jokes;
